on:
  push:
    branches:
      - main
    paths:
      - "subdir/**"
  pull_request:
    paths:
      - "subdir/**"
  workflow_dispatch:


jobs:
  subdir-uv-test-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: subdir
    permissions:
      contents: read
      checks: read
      # for pytest-coverage-comment
      pull-requests: write
      # for super-linter
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history
          fetch-depth: 0
      - name: Install uv
        # https://docs.astral.sh/uv/guides/integration/github/
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "subdir/.python-version"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run Ruff
        # https://docs.astral.sh/ruff/integrations/#github-actions
        run: uv run ruff check --output-format=github .
      - name: Run Ruff changed files(otameshi)
        if: ${{ !cancelled() }}
        uses: astral-sh/ruff-action@v1
        with:
          changed-files: true
          src: subdir
      - name: Run tests
        if: ${{ !cancelled() }}
        run: uv run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
      - name: Pytest coverage comment
        if: ${{ !cancelled() }}
        uses: MishaKav/pytest-coverage-comment@1
        with:
          pytest-coverage-path: subdir/pytest-coverage.txt
          junitxml-path: subdir/pytest.xml
          report-only-changed-files: true
      - name: Super-linter
        if: ${{ !cancelled() }}
        uses: super-linter/super-linter@v7
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}