on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  super-linter-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: read
      # for super-linter
      statuses: write
      # for actions-comment-pull-request
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history
          fetch-depth: 0
      - name: Super-Linter
        # https://github.com/super-linter/super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          CREATE_LOG_FILE: true
          # 	super-linter.log
          SAVE_SUPER_LINTER_OUTPUT: true
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: msg
          filePath: /tmp/lint/super-linter-output/super-linter-summary.md
          comment_tag: super-linter-output-summary
          mode: upsert
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: msg2
          filePath: /tmp/lint/super-linter.log
          comment_tag: super-linter-log
          mode: upsert
