on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  super-linter-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: read
      # for super-linter
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7
